# ASSIGNMENT NO 10

__Question no: 1__

Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [13]:
import numpy as np

x = np.array([7,8])
y = np.array([9,4])

print(x)
print(y)

print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[7 8]
[9 4]
[False  True]
[False  True]
[ True False]
[ True False]


__Question no: 2__

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [29]:

x = np.zeros(10)
print(x,'\n')
y = np.ones(10)
print(y,'\n')
z = np.ones(10)*5
print(z,'\n')


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.] 



__Question no: 3__

Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [45]:
x = np.array([[3,2],[6,5]])
print(x)
s = np.sum(x)
print("Sum of all element of array is: ", s)
c = np.sum(x,axis = 0)
print("Sum of each column is : " , c)
r = np.sum(x,axis = 1)
print("Sum of each row is: ", r)

[[3 2]
 [6 5]]
Sum of all element of array is:  16
Sum of each column is :  [9 7]
Sum of each row is:  [ 5 11]


__Question no:4__

Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [62]:

add = np.add(1.4,3.5)
print("Addition is : ", add)

sub = np.subtract(5.9,1.2)
print("Subtraction is: ", sub)

mul= np.multiply(7.8,1.2)
print("Multiplication is: ",mul)

div = np.divide(4.0,2.0)
print("Division is: ",div)


Addition is :  4.9
Subtraction is:  4.7
Multiplication is:  9.36
Division is:  2.0


__Question no: 5__

Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [24]:
import numpy as np
angles = np.array((0,30,45,60,90))

sine = np.sin(angles*np.pi / 180)
print(sine,'\n')

cosine =np.cos(angles*np.pi/180)
print(cosine,'\n')

tangent = np.tan(angles*np.pi/180)
print(tangent,'\n')

[0.         0.5        0.70710678 0.8660254  1.        ] 

[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17] 

[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16] 



__Question no: 6__

Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [30]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Rohit', 'amit', 'rahul', 'panda', 'shubham', 'sanchit'],
        'score': [19,18,17,9,10,15],
        'attempts': [1, 2,2,4,3,1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f']

d = pd.DataFrame(exam_data , index=labels)
print(d)

      name  score  attempts qualify
a    Rohit     19         1     yes
b     amit     18         2      no
c    rahul     17         2     yes
d    panda      9         4      no
e  shubham     10         3      no
f  sanchit     15         1     yes


__Question no: 7__

Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [31]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Rohit', 'amit', 'rahul', 'panda', 'shubham', 'sanchit'],
        'score': [19,18,17,9,10,15],
        'attempts': [1, 2,2,4,3,1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f']

d = pd.DataFrame(exam_data , index=labels)
print("Select specific columns: ")
print(d[['name','score']])

Select specific columns: 
      name  score
a    Rohit     19
b     amit     18
c    rahul     17
d    panda      9
e  shubham     10
f  sanchit     15


__Question no: 8__

Write a Pandas program to join the two given dataframes along rows and assign all data.

In [35]:
import pandas as pd

stud1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Rohit', 'amit', 'rahul', 'shubham', 'sanchit'],
        'marks': [200, 210, 190, 222, 199]})

stud2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['rohan','tejas','suraj','vishal','navin'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(stud1)
print("-------------------------------------")
print(stud2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([stud1, stud2])
print(result_data)

Original DataFrames:
  student_id     name  marks
0         S1    Rohit    200
1         S2     amit    210
2         S3    rahul    190
3         S4  shubham    222
4         S5  sanchit    199
-------------------------------------
  student_id    name  marks
0         S4   rohan    201
1         S5   tejas    200
2         S6   suraj    198
3         S7  vishal    219
4         S8   navin    201

Join the said two dataframes along rows:
  student_id     name  marks
0         S1    Rohit    200
1         S2     amit    210
2         S3    rahul    190
3         S4  shubham    222
4         S5  sanchit    199
0         S4    rohan    201
1         S5    tejas    200
2         S6    suraj    198
3         S7   vishal    219
4         S8    navin    201


__Question no: 9__

Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [36]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

df = pd.DataFrame({
'ord_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'salesman_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})

print("Original Orders DataFrame:")
print(df)
print("\nMissing values of the said dataframe:")
print(df.isna())

Original Orders DataFrame:
     ord_no  purch_amt    ord_date  customer_id  salesman_id
0   70001.0     150.50  2012-10-05         3002       5002.0
1       NaN     270.65  2012-09-10         3001       5003.0
2   70002.0      65.26         NaN         3001       5001.0
3   70004.0     110.50  2012-08-17         3003          NaN
4       NaN     948.50  2012-09-10         3002       5002.0
5   70005.0    2400.60  2012-07-27         3001       5001.0
6       NaN    5760.00  2012-09-10         3001       5001.0
7   70010.0    1983.43  2012-10-10         3004          NaN
8   70003.0    2480.40  2012-10-10         3003       5003.0
9   70012.0     250.45  2012-06-27         3002       5002.0
10      NaN      75.29  2012-08-17         3001       5003.0
11  70013.0    3045.60  2012-04-25         3001          NaN

Missing values of the said dataframe:
    ord_no  purch_amt  ord_date  customer_id  salesman_id
0    False      False     False        False        False
1     True      False    

__Question no: 10__

Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [39]:
import pandas as pd
data = pd.Series([10,20,30,40,50])
print(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64
